from sample import *
funcList = [
  "Robot Hardware Setup",
  calibrateJoint,
  " ",
  "OnOff",
  servoOn,
  servoOff,
  servoOnHands,
  servoOffHands,
  EngageProtectiveStop,
  DisengageProtectiveStop,
  gazeFixerOn,
  gazeFixerOff,
  collisionCheckOn,
  collisionCheckOff,
  " ",
  "Play Patterns:",
  goInitial,
  goOffPose,
  ikTest,
  ikTest_interrupt,
  ikTest_spline,
  testPattern,
  " ", 
  "etc:",
  getVersion,
  saveLog,
  reboot,
  shutdown,
  " ",
  "move LARM:",
  LARM_X_P10mm,
  LARM_X_P05mm,
  LARM_X_M05mm,
  LARM_X_M10mm,
  " ",
  LARM_Y_P10mm,
  LARM_Y_P05mm,
  LARM_Y_M05mm,
  LARM_Y_M10mm,
  " ",
  LARM_Z_P10mm,
  LARM_Z_P05mm,
  LARM_Z_M05mm,
  LARM_Z_M10mm,
  " ",
  printConfigurationR,
  printConfigurationL,
  " ",
  "Grasper:",
  rhandOpen,
  rhandOpen60,
  rhandOpen30,
  rhandClose,
  " ",
  lhandOpen,
  lhandOpen60,
  lhandOpen30,
  lhandClose,
]
